apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: "registry.ng.bluemix.net/dakar9499ns/nodeapp:0.0.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
